name: Publish Dev Docker Image on Main Push

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set metadata
        run: |
          echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push dev tag (multi-arch)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/rwddt_eureka:dev \
            --label "org.opencontainers.image.version=dev" \
            --label "org.opencontainers.image.created=${CREATED}" \
            --label "org.opencontainers.image.revision=${REVISION}" \
            .
